address_list:
    path:     /address/list/{page}
    defaults: { _controller: DitaTrackingBundle:Address:list, page:0 }
    requirements: { page: \d+ }
address_edit:
    path:     /address/edit/{id}
    defaults: { _controller: DitaTrackingBundle:Address:edit }
    requirements: {}
address_show:
    path:     /address/show
    defaults: { _controller: DitaTrackingBundle:Address:show }

address_remove:
    path:     /address/remove
    defaults: { _controller: DitaTrackingBundle:Address:remove }
