<?php

namespace Dita\TrackingBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TrackingRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TrackingRepository extends DocumentRepository
{
}
